package com.sqlteacher.application.event;

public enum LearningEventType {
    SQL_EXECUTION,
    SQL_RISK_BLOCKED,
    SQL_CONFIRMATION_ISSUED,
    SQL_CONFIRMED,
    SQL_CONFIRMATION_CANCELLED,
    AI_SQL_GENERATED,
    AI_GENERATION_FAILED,
    EXERCISE_ATTEMPT,
    EXERCISE_PASSED,
    EXERCISE_FAILED,
    EXERCISE_HINT_USED,
    ACTIVITY_ATTEMPT,
    ACTIVITY_PASSED,
    ACTIVITY_FAILED,
    KNOWLEDGE_SEARCHED
}
